module Lang
#Different languages, just cause
	EN = [
	"Chess",
	"by",
	"Board",
	"Info",
	"Main Menu",
	"Start Game",
	"Options",
	"Quit",
	"Back",
	"Color Mode",
	"Theme",
	"Language",
	"Language Options",
	"Thanks",
	"for",
	"Playing",
	"Game Menu",
	"Continue Game",
	"New Game",
	"Load Game",
	"Here you can choose to continue, load or make a new game",
	"Really start a new game?",
	"The AI is really dumb, it only makes random moves",
	"Singleplayer",
	"Multiplayer",
	"Choose a gamemode",
	"Pick one of your saves",
	"Some options you can change",
	"Choose the language you like",
	"Choose the theme you like the most",
	"Choose the colormode that fits your terminal",
	"Welcome to my version of chess!",
	"Last Move: ",
	"Make a Move",
	"Save Game",
	"Give Up",
	"Make a move?",
	"Only Player 1 can save",
	"Enter a name (Only a-z and 0-9, no longer than 10 chars)",
	"Invalid input",
	"Press any key to continue",
	"Press any key, resumes automatically in ",
	"Black",
	"White",
	"Wins!",
	"Draw!",
	"Pick a Promotion",
	"Queen",
	"Rook",
	"Bishop",
	"Knight",
	"CAPTURE",
	"CASTLING",
	
	] #52

	DE = [
	"Schach",
	"von",
	"Brett",
	"Information",
	"Hauptmenü",
	"Spiel Starten",
	"Optionen",
	"Beenden",
	"Zurück",
	"Farbmodus",
	"Farbmotiv",
	"Sprache",
	"Sprachoptionen",
	"Danke",
	"fuers",
	"Spielen",
	"Spielmenu",
	"Fortsetzen",
	"Neues Spiel",
	"Spiel Laden",
	"Hier kannst du das Spiel laden, fortsetzen oder neu starten",
	"Willst du wirklich neu starten?",
	"Die KI ist wirklich simpel und kann nur zufällige Züge machen",
	"Einzelspieler",
	"Mehrspieler",
	"Such dir einen Modus aus",
	"Such dir einen deiner Spielstände aus",
	"Ein paar Optionen zum ändern",
	"Such dir die Sprache aus, die dir gefällt",
	"Triff deine Farbwahl",
	"Such dir den Farbmodus aus, der mit deinem Terminal kompatibel ist",
	"Willkommen bei meiner Version von Schach!",
	"Letzter Zug: ",
	"Mach einen Zug",
	"Spiel speichern",
	"Aufgeben",
	"Willst du einen Zug machen?",
	"Nur Spieler 1 kann speichern",
	"Gib einen Namen für den Spielstand ein (Nur a-z, 0-9 und nicht länger als 10 Zeichen)",
	"Ungültige Eingabe",
	"Drück eine Taste zum fortsetzen",
	"Drück eine Taste, setzt automatisch fort in ",
	"Schwarz",
	"Weiss",
	"Gewinnt!",
	"Unentschieden!",
	"Such dir eine Beförderung aus",
	"Dame",
	"Turm",
	"Läufer",
	"Springer",
	"SCHLÄGT",
	"ROCHADE",
	
	]#52

	$string=EN

	def change_lang(language)
		$string=EN if language == "en"
		$string=DE if language == "de"
	end

end